version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - prisma-db:/usr/src/app/prisma/
    environment:
      NODE_ENV: development

volumes:
  prisma-db:
