name: Deploy to Droplet

on:
  push:
    branches:
      - main # Adjust to match your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t minting-api-backend:${{ github.sha }} .

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to DockerHub
        run: docker push minting-api-backend:${{ github.sha }}

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            docker pull minting-api-backend:${{ github.sha }}
            docker stop minting-api-backend || true
            docker rm minting-api-backend || true
            docker run -d --name minting-api-backend -p 80:3000 minting-api-backend:${{ github.sha }}
